### ISSUE TITLE
Error when update to 3.4.0

### ISSUE THREAD

**Issue by s-fog** [MohmmedAshraf/nova-hidden-field#4]
They realize new Feature on version 3.4.0
https://nova.laravel.com/releases
**Added new default method for specifying default values within Fields. #866**
Declaration of Outhebox\NovaHiddenField\HiddenField::default(?string $value = NULL) should be compatible with Laravel\Nova\Fields\Field::default($callback)

Just need to change this method

**Comment by muhghazaliakbar** [comment]
Yeah, the `default()` method is conflicted with the latest nova version. I have created a PR for that #5 and you can temporary use that before get accepted by @MohmmedAshraf
