### ISSUE TITLE
Can't use default value

### ISSUE THREAD

**Issue by coroo** [MohmmedAshraf/nova-hidden-field#6]
Hi, 

thank you for this cool package. Actually, I have problem when using hiddenfield with default value. 
```
use Outhebox\NovaHiddenField\HiddenField;

HiddenField::make('debit_kredit', 'debit_kredit')->default('kredit'),
```

the error in my app looks like this:
<img width="564" alt="Screen Shot 2020-06-07 at 12 47 04" src="https://user-images.githubusercontent.com/13533557/83961448-51a0cf00-a8bd-11ea-8d91-bbd6df00e7f1.png">

**Comment by coroo** [comment]
Ok, found the issue.

After check this file: https://github.com/MohmmedAshraf/nova-hidden-field/blob/master/src/HiddenField.php#L22 , the default value can be called as:
```
use Outhebox\NovaHiddenField\HiddenField;

HiddenField::make('debit_kredit', 'debit_kredit')->defaultValue('kredit'),
```

Thank you.

**Comment by MohmmedAshraf** [comment]
Thank you @coroo I've update this in Readme.md file also so new user will never face this issue.
